# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SatHubAI
                                 A QGIS plugin
 This plugin automates the download of satellite data from multiple providers and detects specific features in the data with AI.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-16
        copyright            : (C) 2024 by Theo Kretz
        email                : theokretz2001@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SatHubAI class from file SatHubAI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sathub_ai import SatHubAI
    return SatHubAI(iface)
